### ISSUE TITLE
gtap 0.4是不是已经强制 https了

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#56]
```
What steps will reproduce the problem?
1.没有以前的配置选项 secure : always 了
2.每次 http://XXX.appspot.com 打开都会自动跳转到 
https://XXX.appspot.com
3.gtap 0.4是不是已经强制 
https了？这是不是意味着非翻的童鞋，或者是未有找到可以IP�
��hosts童鞋将无缘gtap？

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
 gtap 0.4

Please provide any additional information below.

```

Original issue reported on code.google.com by `Justice2...@gmail.com` on 6 Aug 2010 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
默认情况下非晶态内容的secure选项还是有的，不想使用https，
可以将app.yaml文件中的那一行去掉。
以下是完整的app.yaml文件默认情况下的内容：
application: gtapserver1
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static 

- url: /.*
  script: main.py
  secure: always

```

Original comment by `rui7905` on 6 Aug 2010 at 12:35
- Changed state: **WontFix**
